package com.bankcomm.shirodemo.dao;

import com.bankcomm.shirodemo.bean.User;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

/**
 * @author Tianqi.Zhang
 * @date 2018/11/28
 */
@Mapper
@Repository
public interface UserMapper {
    /**
     * 根据用户名查询用户信息
     *
     * @return
     * @param username
     */
    User selectByUsername(String username);
    /**
     * 注册用户
     *
     */
    Integer insert(User record);

    void getRole();

    //    int insertSelective(User record);
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table table_user
//     *
//     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
//     */
//    int deleteByPrimaryKey(Integer id);
//

//

//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table table_user
//     *
//     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
//     */
//    User selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table table_user
//     *
//     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
//     */
//    int updateByPrimaryKeySelective(User record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table table_user
//     *
//     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
//     */
//    int updateByPrimaryKey(User record);


}