package com.bankcomm.shirodemo.mapper;

import com.bankcomm.shirodemo.bean.User;

/**
 * @author Tianqi.Zhang
 * @date 2018/11/28
 */
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_user
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_user
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_user
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_user
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_user
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_user
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    int updateByPrimaryKey(User record);
}