package com.bankcomm.shirodemo.mapper;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.id
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.username
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.password
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.salt
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.role
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.create_time
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.last_login_time
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_user.status
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.id
     *
     * @return the value of table_user.id
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.id
     *
     * @param id the value for table_user.id
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.username
     *
     * @return the value of table_user.username
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.username
     *
     * @param username the value for table_user.username
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.password
     *
     * @return the value of table_user.password
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.password
     *
     * @param password the value for table_user.password
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.salt
     *
     * @return the value of table_user.salt
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.salt
     *
     * @param salt the value for table_user.salt
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.role
     *
     * @return the value of table_user.role
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.role
     *
     * @param role the value for table_user.role
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.create_time
     *
     * @return the value of table_user.create_time
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.create_time
     *
     * @param createTime the value for table_user.create_time
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.last_login_time
     *
     * @return the value of table_user.last_login_time
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.last_login_time
     *
     * @param lastLoginTime the value for table_user.last_login_time
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_user.status
     *
     * @return the value of table_user.status
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_user.status
     *
     * @param status the value for table_user.status
     *
     * @mbg.generated Wed Nov 28 14:29:54 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}